### ISSUE TITLE
Request to add extraction (96-well) plate IDs and well positions to pre-preparation info

### ISSUE THREAD

**Issue by justinshaffer** [qiita-spots/qp-knight-lab-processing#42]
Hello!

I suggest to add the extraction plate ID and sample well position to the pre-preparation file so that it can be tracked through analyses. This will allow us to determine if there are patterns related to extraction, which I think is currently difficult to determine as the 96-well plate information is currently omitted.

Thanks!

**Comment by antgonza** [comment]
Thank you @justinshaffer! A couple of questions:
1. Do you or @mmbryant23 know what's the column name that stores this information? 
2. Is this for metaT/metaG, amplicon, both, other?

**Comment by mmbryant23** [comment]
@antgonza
For context, we used to track 96-well ID info using the old mapping file generation script. However, with the development of Jake's miniPCR protocol using 384-well plates, we decided to move forward with using the 384-well ID: If we needed to re-pool certain samples from a 384-well plate when the pre-preparation sheet contained 96-well plate information, lots of manual extra steps were required in order to convert the 96-well ID to a 384-well plate format, or vice versa.
1. Currently, the 384-well information is located in the well_ID column. We would need to make a new column for the 96-well info, possibly gDNA_well_ID or something similar that we can infer it is in a 96-well format. This information will likely be extracted from a step in the notebook.
2. @justinshaffer Do you know if this information is included in the metaG/metaT preparation sheet if we are compressing the 4x96-well gDNA in the same fashion? If they are important for the pre-preparation information for amplicon, I'd imagine they would be important for metaG/T as well?

**Comment by antgonza** [comment]
Thank you for the information. Just to confirm, is the use of the 96-well discontinued (replace by 384-well) in the wet-lab, being reintroduced or something else?

**Comment by mmbryant23** [comment]
No, it's not discontinued entirely as we are still plating and extracting in 96-well plates - It's important information to add.

To add a note to Justin's suggestion of 'extraction plate ID ': We do have sample_plate already, which contains the name of the 96-well plate (ex: Isolation_Dorm_13957_Plate_1), so that is already tracked.

**Comment by charles-cowart** [comment]
I think we've made progress on this issue, as we did add a well_id_96 column to the pre-prep files. However, I'm not sure that we've done anything with the extraction plate id. What do you think, @mmbryant23 ?

**Comment by mmbryant23** [comment]
@charles-cowart The extraction plate ID can be found under sample_plate in the pre-preparation file, so we have that information already. Thanks for checking!

**Comment by charles-cowart** [comment]
Thanks @mmbryant23 ! I'll close this issue then.
